### ISSUE TITLE
Android Studio and Maven support

### ISSUE THREAD

**Issue by neosimsim** [AzureAD/rms-sdk-ui-for-android#1]
I would much appreciate it if you add all libraries to maven not just ADAL. That would make usage much easier especially with Android Studio, which the new default IDE for Android.

So I only have to add something like 

``` gradle
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile 'com.microsoft.aad:adal:1.1.1' // <-- This already works
    compile 'com.microsoft.rightsmanagement:rightsmanagement:x.x.x' // <-- That would be new
    compile 'com.microsoft.rightsmanagement:uilib:x.x.x' // <-- That would be new
}
```

to my build.gradle.

Thank you very much

**Comment by raeitan** [comment]
Hey neosimsim, 
we currently do not have approval to put com.microsoft.rightsmanagement in github, when we do we add it to github we will register the packages to Maven. thanks
